version: '3'
services:
  zookeeper1: # https://hub.docker.com/_/zookeeper
    image: zookeeper:3.7
    container_name: zookeeper1
    restart: always
    hostname: zookeeper1
    ports:
      - 17286:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper186:2888:3888;2181
      # ZOO_TICK_TIME: 2000
      # ZOO_INIT_LIMIT: 5
      # ZOO_SYNC_LIMIT: 2
      # ZOO_MAX_CLIENT_CNXNS: 60
      # ZOO_STANDALONE_ENABLED: true
      # ZOO_ADMINSERVER_ENABLED: true
      # ZOO_AUTOPURGE_PURGEINTERVAL: 0
      # ZOO_AUTOPURGE_SNAPRETAINCOUNT: 3
      # ZOO_4LW_COMMANDS_WHITELIST: srvr

  zookeeper2: # https://hub.docker.com/_/zookeeper
    image: zookeeper:3.7
    container_name: zookeeper2
    restart: always
    hostname: zookeeper2
    ports:
      - 17295:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper195:2888:3888;2181
      # ZOO_TICK_TIME: 2000
      # ZOO_INIT_LIMIT: 5
      # ZOO_SYNC_LIMIT: 2
      # ZOO_MAX_CLIENT_CNXNS: 60
      # ZOO_STANDALONE_ENABLED: true
      # ZOO_ADMINSERVER_ENABLED: true
      # ZOO_AUTOPURGE_PURGEINTERVAL: 0
      # ZOO_AUTOPURGE_SNAPRETAINCOUNT: 3
      # ZOO_4LW_COMMANDS_WHITELIST: srvr

  zookeeper3: # https://hub.docker.com/_/zookeeper
    image: zookeeper:3.7
    container_name: zookeeper3
    restart: always
    hostname: zookeeper3
    ports:
      - 17273:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper173:2888:3888;2181
      # ZOO_TICK_TIME: 2000
      # ZOO_INIT_LIMIT: 5
      # ZOO_SYNC_LIMIT: 2
      # ZOO_MAX_CLIENT_CNXNS: 60
      # ZOO_STANDALONE_ENABLED: true
      # ZOO_ADMINSERVER_ENABLED: true
      # ZOO_AUTOPURGE_PURGEINTERVAL: 0
      # ZOO_AUTOPURGE_SNAPRETAINCOUNT: 3
      # ZOO_4LW_COMMANDS_WHITELIST: srvr

  kafka-059:
    image: wurstmeister/kafka
    container_name: kafka-059
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181
      # KAFKA_CREATE_TOPICS: 'sum:1:1, pow:1:1' # Topic명:Partition개수:Replica개수
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '17259:9092'
    depends_on:
      - zookeeper1

  
  kafka-046:
    image: wurstmeister/kafka
    container_name: kafka-046
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper2:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '17246:9092'
    depends_on:
      - zookeeper2

  
  kafka-078:
    image: wurstmeister/kafka
    container_name: kafka-078
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper3:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '17278:9092'
    depends_on:
      - zookeeper3